name: "docs"
on: [push]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build docs
        run: |
          cd docs
          sphinx-apidoc -f -o source ../purenes
          make html
      - name: Deploy to GitHub Pages
        # Don't deploy unless this is the main branch
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs/build/html
